Blog post on affiliations (MT & CSG)
adsabs/adsabs.github.io pull request #277
Opened 2021-04-15 17:16 UTC by seasidesparrow

2021-04-20 16:05 UTC, kelockhart requested changes
Looks really good! I have a few formatting comments, plus just a couple readability ones. Otherwise it's about good to go.

2021-04-20 16:05 UTC, kelockhart commented on blog/_posts/2021-04-15-affils-update.md
> +There are comparatively few publications by authors affiliated with these colleges: Salish Kootenai College (Montana), Northwest Indian College (Pacific NW), Din&eacute; College (Arizona) and Fond du
The colon in the first sentence makes me think the four colleges listed have few publications, but the end of the sentence makes it sound like those 4 have the most. Can you clarify? If it's that these are the most represented, changing the colon to a period or semi-colon is all that's needed (probably a period - there are a lot of semi-colons in this subsection already).

2021-04-20 16:05 UTC, kelockhart commented on blog/_posts/2021-04-15-affils-update.md
> +If you find affiliation IDs that aren't correct, please let us know.  Likewise if there are affiliations that you think should be included or better disambiguated as parents and children, please get
I like this specific call for action/help! Add a link to the adshelp@ email somewhere in this paragraph.

2021-04-22 13:29 UTC, seasidesparrow commented on blog/_posts/2021-04-15-affils-update.md
> +We have also added affiliation IDs for a partial list of Tribal Colleges and Universities (TCUs), primarily those in the United States that are currently represented in the ADS Literature.  The list
Modified slightly, and added a short list of non-tribal colleges with significant native american populations.

2021-04-22 14:14 UTC, seasidesparrow commented on blog/_posts/2021-04-15-affils-update.md
> +* *inst*: This field is a shortcut to enable you to search for institutions without requiring you to know their parent.  It also allows you to search the affiliation identifications curated by the AD
I expanded the discussion under "What are affiliations" to introduce the concept of parents and children.

2021-04-30 18:48 UTC, merged